name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ruff
        run: ruff check .
      - name: Black (check)
        run: black --check .
      - name: Tests
        run: pytest -q
      - name: Bandit
        run: bandit -c pyproject.toml -r services